[package]
name = "media"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
mpp = []
dvpp = []
rga = []
hw-snap-mpp = ["mpp", "rga"]
hw-snap-vt = []
hw-snap-dvpp = ["dvpp"]

[dependencies]
types = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
base64 = { workspace = true }
percent-encoding = { workspace = true }
parking_lot = { workspace = true }
url = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
image = { workspace = true }
libc = { workspace = true }
md-5 = "0.10"
retina = "0.4.20"
futures = "0.3"
