[package]
name = "pipeline"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
types = { workspace = true }
media = { workspace = true }
infer = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
image = { workspace = true }
uuid = { workspace = true }
bytes = { workspace = true }
libc = { workspace = true }
serde = { workspace = true }
tokio-util = "0.7"

[dev-dependencies]
db = { workspace = true }
sea-orm = { workspace = true }
